name: Netshare tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.6"
          cache: 'pip'  # Cache the dependencies installation
          cache-dependency-path: setup.py
      - uses: awalsh128/cache-apt-pkgs-action@latest  # Install linux dependencies for pcap header files
        with:
          packages: libpcap-dev
          version: 1.0
      - name: Install dependencies
        run: |
          pip install -e .[dev]
      - uses: actions/cache@v3  # Cache the pre-commit environment
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: pre-commit on all files changed from the main branch
        run: |
          git fetch origin new_dataset
          pre-commit run --files $(git diff --name-only origin/new_dataset)
      - name: Test with pytest
        run: |
          pytest test/
